import type { JSX } from "react";
import {
  FiActivity,
  FiAirplay,
  FiAlertCircle,
  FiAlertOctagon,
  FiAlertTriangle,
  FiAlignCenter,
  FiAlignJustify,
  FiAlignLeft,
  FiAlignRight,
  FiAnchor,
  FiAperture,
  FiBookOpen,
  FiDroplet,
  FiEdit3,
  FiFastForward,
  FiArchive,
  FiArrowDown,
  FiArrowDownCircle,
  FiArrowDownLeft,
  FiArrowDownRight,
  FiArrowLeft,
  FiArrowLeftCircle,
  FiArrowRight,
  FiArrowRightCircle,
  FiArrowUp,
  FiArrowUpCircle,
  FiArrowUpLeft,
  FiArrowUpRight,
  FiAtSign,
  FiAward,
  FiBarChart2,
  FiBarChart,
  FiBattery,
  FiBatteryCharging,
  FiBell,
  FiBellOff,
  FiBluetooth,
  FiBold,
  FiBook,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCamera,
  FiCameraOff,
  FiCast,
  FiCheck,
  FiCheckCircle,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsLeft,
  FiChevronsRight,
  FiChevronsUp,
  FiDisc,
  FiCircle,
  FiClipboard,
  FiCloud,
  FiCloudDrizzle,
  FiCloudLightning,
  FiCloudOff,
  FiCloudRain,
  FiCloudSnow,
  FiCodepen,
  FiCpu,
  FiDivideCircle,
  FiExternalLink,
  FiCornerDownLeft,
  FiCornerUpLeft,
  FiCornerDownRight,
  FiCornerUpRight,
  FiCornerLeftDown,
  FiCornerLeftUp,
  FiCornerRightDown,
  FiCornerRightUp,
  FiCreditCard,
  FiCrop,
  FiCrosshair,
  FiDatabase,
  FiDelete,
  FiDivide,
  FiDivideSquare,
  FiDollarSign,
  FiDownload,
  FiEdit,
  FiEdit2,
  FiEye,
  FiEyeOff,
  FiFacebook,
  FiFeather,
  FiFigma,
  FiFile,
  FiFileMinus,
  FiFilePlus,
  FiItalic,
  FiKey,
  FiLayers,
  FiLifeBuoy,
  FiLink,
  FiLink2,
  FiLinkedin,
  FiList,
  FiLoader,
  FiLock,
  FiLogIn,
  FiLogOut,
  FiMail,
  FiMap,
  FiMapPin,
  FiMaximize,
  FiMinimize,
  FiMeh,
  FiMenu,
  FiMessageCircle,
  FiMessageSquare,
  FiMic,
  FiMicOff,
  FiMove,
  FiMinimize2,
  FiMinus,
  FiMinusCircle,
  FiMinusSquare,
  FiMonitor,
  FiMoon,
  FiMoreHorizontal,
  FiMoreVertical,
  FiMousePointer,
  FiMusic,
  FiOctagon,
  FiPaperclip,
  FiPause,
  FiMaximize2,
  FiPercent,
  FiPhone,
  FiPhoneCall,
  FiPhoneForwarded,
  FiPhoneIncoming,
  FiPhoneMissed,
  FiPhoneOff,
  FiPhoneOutgoing,
  FiPieChart,
  FiPlay,
  FiPlayCircle,
  FiPlus,
  FiPlusCircle,
  FiPlusSquare,
  FiPocket,
  FiPower,
  FiPrinter,
  FiRefreshCcw,
  FiRefreshCw,
  FiRepeat,
  FiRewind,
  FiRotateCcw,
  FiRotateCw,
  FiRss,
  FiSave,
  FiScissors,
  FiSearch,
  FiSend,
  FiServer,
  FiSettings,
  FiShare,
  FiShare2,
  FiShield,
  FiShieldOff,
  FiShoppingBag,
  FiShoppingCart,
  FiShuffle,
  FiSidebar,
  FiSkipBack,
  FiSkipForward,
  FiSlack,
  FiSlash,
  FiSliders,
  FiSmartphone,
  FiSmile,
  FiSpeaker,
  FiPenTool,
  FiSquare,
  FiStar,
  FiTarget,
  FiSun,
  FiUpload,
  FiTag,
  FiTerminal,
  FiThermometer,
  FiThumbsDown,
  FiThumbsUp,
  FiTrash2,
  FiTrash,
  FiTrello,
  FiTrendingDown,
  FiTrendingUp,
  FiTriangle,
  FiTruck,
  FiTv,
  FiTwitch,
  FiTwitter,
  FiType,
  FiUmbrella,
  FiUnderline,
  FiUnlock,
  FiHeadphones,
  FiUser,
  FiUserCheck,
  FiUserMinus,
  FiUserPlus,
  FiUsers,
  FiUserX,
  FiVideo,
  FiVideoOff,
  FiVoicemail,
  FiVolume,
  FiVolume1,
  FiVolume2,
  FiVolumeX,
  FiWatch,
  FiWifi,
  FiX,
  FiZap,
  FiZoomIn,
  FiZoomOut,
  FiToggleLeft,
  FiToggleRight,
  FiTool,
  FiWifiOff,
  FiWind,
  FiXOctagon,
  FiXSquare,
  FiYoutube,
} from "react-icons/fi";
import { SlCalender } from "react-icons/sl";
import { IoBookOutline, IoGlobeOutline } from "react-icons/io5";
import { FaPodcast, FaRegCompass } from "react-icons/fa6";
import { RxCopy } from "react-icons/rx";
import { LucideCloudDownload, LucideHelpCircle, LucideHome } from "lucide-react";
import { 
  LuFile,        
  LuFilm,        
  LuFilter,      
  LuFlag,        
  LuFolder,      
  LuFolderPlus,  
  LuVolumeX,     
  LuFrown,       
  LuGift,        
  LuGitBranch,      
  LuGitlab,      
  LuGlobe,       
  LuHardDrive,   
  LuHash,        
  LuHeadphones,  
  LuHeart,       
  LuHexagon,      
  LuImage,       
  LuInbox,       
  LuInfo,        
  LuInstagram,    
  LuGithub,
  LuGitCommitHorizontal,
  LuFolderMinus,
  LuGitPullRequest,
  LuGitMerge,
  LuLayoutGrid,
  LuNavigation2,
  LuZapOff,
} from "react-icons/lu";
import { BsCursor, BsSunrise, BsSunset } from "react-icons/bs";
import { MdOutlinePauseCircle } from "react-icons/md";
import { GoTable, GoXCircle } from "react-icons/go";
type IconItem = {
  name: string;
  svg: JSX.Element;
};

export const featherIcons: IconItem[] = [
  { name: "o", svg: <FiActivity size={24} /> },
  { name: "n", svg: <FiAirplay size={24} /> },
  { name: "e", svg: <FiAlertCircle size={24} /> },
  { name: "i", svg: <FiAlertOctagon size={24} /> },
  { name: "a", svg: <FiAlertTriangle size={24} /> },
  { name: "l", svg: <FiAlignCenter size={24} /> },
  { name: "s", svg: <FiAlignJustify size={24} /> },
  { name: "c", svg: <FiAlignLeft size={24} /> },
  { name: "u", svg: <FiAlignRight size={24} /> },
  { name: "g", svg: <FiAnchor size={24} /> },
  { name: "d", svg: <FiAperture size={24} /> },
  { name: "k", svg: <FiArchive size={24} /> },
  { name: "p", svg: <FiArrowDown size={24} /> },
  { name: "h", svg: <FiArrowDownCircle size={24} /> },
  { name: "x", svg: <FiArrowDownLeft size={24} /> },
  { name: "y", svg: <FiArrowDownRight size={24} /> },
  { name: "L", svg: <FiArrowLeft size={24} /> },
  { name: "v", svg: <FiArrowLeftCircle size={24} /> },
  { name: "w", svg: <FiArrowRight size={24} /> },
  { name: "f", svg: <FiArrowRightCircle size={24} /> },
  { name: "W", svg: <FiArrowUp size={24} /> },
  { name: "C", svg: <FiArrowUpCircle size={24} /> },
  { name: "F", svg: <FiArrowUpLeft size={24} /> },
  { name: "B", svg: <FiArrowUpRight size={24} /> },
  { name: "j", svg: <FiAtSign size={24} /> },
  { name: "M", svg: <FiAward size={24} /> },
  { name: "z", svg: <FiBarChart2 size={24} /> },
  { name: "A", svg: <FiBarChart size={24} /> },
  { name: "V", svg: <FiBattery size={24} /> },
  { name: "H", svg: <FiBatteryCharging size={24} /> },
  { name: "S", svg: <FiBell size={24} /> },
  { name: "m", svg: <FiBellOff size={24} /> },
  { name: "P", svg: <FiBluetooth size={24} /> },
  { name: "T", svg: <FiBold size={24} /> },
  { name: "U", svg: <FiBook size={24} /> },
  { name: "D", svg: <FiBookOpen size={24} /> },
  { name: "R", svg: <FiBookmark size={24} /> },
  { name: "b", svg: <FiBox size={24} /> },
  { name: "O", svg: <FiBriefcase size={24} /> },
  { name: "G", svg: <FiCalendar size={24} /> },
  { name: "q", svg: <FiCamera size={24} /> },
  { name: "I", svg: <FiCameraOff size={24} /> },
  { name: "E", svg: <FiCast size={24} /> },
  { name: "_", svg: <FiCheck size={24} /> },
  { name: "X", svg: <FiCheckCircle size={24} /> },
  { name: "Z", svg: <FiChevronDown size={24} /> },
  { name: "N", svg: <FiChevronLeft size={24} /> },
  { name: "J", svg: <FiChevronRight size={24} /> },
  { name: "K", svg: <FiChevronLeft size={24} /> },
  { name: "Y", svg: <FiChevronUp size={24} /> },
  { name: "Q", svg: <FiChevronDown size={24} /> },
  { name: "$", svg: <FiChevronsLeft size={24} /> },
  { name: "tt", svg: <FiChevronsRight size={24} /> },
  { name: "rt", svg: <FiChevronsUp size={24} /> },
  { name: "ot", svg: <FiDisc size={24} /> },
  { name: "nt", svg: <FiCircle size={24} /> },
  { name: "et", svg: <FiClipboard size={24} /> },
  { name: "it", svg: <FiClipboard size={24} /> },
  { name: "gt", svg: <FiCloud size={24} /> },
  { name: "at", svg: <FiCloudDrizzle size={24} /> },
  { name: "lt", svg: <FiCloudLightning size={24} /> },
  { name: "st", svg: <FiCloudOff size={24} /> },
  { name: "ct", svg: <FiCloudRain size={24} /> },
  { name: "ut", svg: <FiCloudSnow size={24} /> },
  { name: "dt", svg: <FiChevronsRight size={24} /> },
  { name: "kt", svg: <FiCodepen size={24} /> },
  { name: "ht", svg: <FiBox size={24} /> },
  { name: "xt", svg: <SlCalender size={24} /> },
  { name: "yt", svg: <IoBookOutline size={24} /> },
  { name: "pt", svg: <FiCpu size={24} /> },
  { name: "vt", svg: <FaRegCompass size={24} /> },
  { name: "Lt", svg: <RxCopy size={24} /> },
  { name: "ft", svg: <FiCornerDownLeft size={24} /> },
  { name: "wt", svg: <FiCornerUpLeft size={24} /> },
  { name: "Ct", svg: <FiCornerDownRight size={24} /> },
  { name: "Ft", svg: <FiCornerUpRight size={24} /> },
  { name: "Bt", svg: <FiCornerLeftDown size={24} /> },
  { name: "Wt", svg: <FiCornerLeftUp size={24} /> },
  { name: "jt", svg: <FiCornerRightDown size={24} /> },
  { name: "Mt", svg: <FiCornerRightUp size={24} /> },
  { name: "At", svg: <FiCpu size={24} /> },
  { name: "zt", svg: <FiCreditCard size={24} /> },
  { name: "Ht", svg: <FiCrop size={24} /> },
  { name: "Vt", svg: <FiCrosshair size={24} /> },
  { name: "mt", svg: <FiDatabase size={24} /> },
  { name: "St", svg: <FiDelete size={24} /> },
  { name: "Pt", svg: <FiDisc size={24} /> },
  { name: "Ut", svg: <FiDivide size={24} /> },
  { name: "Tt", svg: <FiDivideCircle size={24} /> },
  { name: "Dt", svg: <FiDivideSquare size={24} /> },
  { name: "Rt", svg: <FiDollarSign size={24} /> },
  { name: "Ot", svg: <FiDownload size={24} /> },
  { name: "bt", svg: <LucideCloudDownload size={24} /> },
  { name: "Gt", svg: <IoGlobeOutline size={24} /> },
  { name: "It", svg: <FiDroplet size={24} /> },
  { name: "Xt", svg: <FiEdit size={24} /> },
  { name: "qt", svg: <FiEdit2 size={24} /> },
  { name: "Et", svg: <FiEdit3 size={24} /> },
  { name: "Zt", svg: <FiExternalLink size={24} /> },
  { name: "Nt", svg: <FiEye size={24} /> },
  { name: "_t", svg: <FiEyeOff size={24} /> },
  { name: "Jt", svg: <FiFacebook size={24} /> },
  { name: "Kt", svg: <FiFastForward size={24} /> },
  { name: "Yt", svg: <FiFeather size={24} /> },
  { name: "Qt", svg: <FiFigma size={24} /> },
  { name: "or", svg: <FiFile size={24} /> },
  { name: "$t", svg: <FiFileMinus size={24} /> },
  { name: "tr", svg: <FiFilePlus size={24} /> },

  { name: "rr", svg: <LuFile size={24} /> },
  { name: "nr", svg: <LuFilm  size={24} /> },
  { name: "er", svg: <LuFilter  size={24} /> },
  { name: "ir", svg: <LuFlag  size={24} /> },
  { name: "sr", svg: <LuFolder  size={24} /> },
  { name: "ir", svg: <LuFolderMinus  size={24} /> },
  
  { name: "lr", svg: <LuFolderPlus  size={24} /> },
  { name: "cr", svg: <LuVolumeX  size={24} /> },
  { name: "ur", svg: <LuFrown  size={24} /> },
  { name: "gr", svg: <LuGift  size={24} /> },
  { name: "dr", svg: <LuGitBranch  size={24} /> },
  { name: "kr", svg: <LuGitCommitHorizontal  size={24} /> },
  { name: "hr", svg: <LuGitMerge  size={24} /> },

  { name: "xr", svg: <LuGitPullRequest  size={24} /> },
  { name: "yr", svg: <LuGithub  size={24} /> },
  { name: "pr", svg: <LuGitlab  size={24} /> },
  { name: "vr", svg: <LuGlobe  size={24} /> },
  { name: "Lr", svg: <LuLayoutGrid  size={24} /> },
  
  { name: "fr", svg: <LuHardDrive  size={24} /> },
  { name: "wr", svg: <LuHash  size={24} /> },
  { name: "Cr", svg: <LuHeadphones  size={24} /> },
  { name: "Fr", svg: <LuHeart  size={24} /> },
  { name: "Br", svg: <LucideHelpCircle  size={24} /> },
  { name: "Wr", svg: <LuHexagon  size={24} /> },
  { name: "jr", svg: <LucideHome  size={24} /> },
  { name: "Mr", svg: <LuImage  size={24} /> },
  { name: "Ar", svg: <LuInbox  size={24} /> },
  { name: "zr", svg: <LuInfo  size={24} /> },
  { name: "Hr", svg: <LuInstagram  size={24} /> },
  { name: "Vr", svg: <FiItalic  size={24} /> },

  { name: "mr", svg: <FiKey size={24} /> },
  { name: "Sr", svg: <FiLayers size={24} /> },
  { name: "Pr", svg: <GoTable size={24} /> },
  { name: "Tr", svg: <FiLifeBuoy  size={24} /> },
  { name: "Ur", svg: <FiLink  size={24} /> },
  { name: "Dr", svg: <FiLink2  size={24} /> },

  { name: "Rr", svg: <FiLinkedin size={24} /> },
  { name: "br", svg: <FiList size={24} /> },
  { name: "Or", svg: <FiLoader size={24} /> },
  { name: "Gr", svg: <FiLock  size={24} /> },
  { name: "Ir", svg: <FiLogIn size={24} /> },
  { name: "qr", svg: <FiLogOut size={24} /> },

  { name: "Er", svg: <FiMail size={24} /> },
  { name: "Zr", svg: <FiMap size={24} /> },
  { name: "Xr", svg: <FiMapPin size={24} /> },
  { name: "Nr", svg: <FiMaximize  size={24} /> },
  { name: "_r", svg: <FiMaximize2 size={24} /> },
  { name: "Jr", svg: <FiMeh size={24} /> },

  { name: "Kr", svg: <FiMenu size={24} /> },
  { name: "Yr", svg: <FiMessageCircle size={24} /> },
  { name: "Qr", svg: <FiMessageSquare size={24} /> },
  { name: "t2", svg: <FiMic size={24} /> },
  { name: "$r", svg: <FiMicOff size={24} /> },
  { name: "o2", svg: <FiMinimize size={24} /> },

  { name: "r2", svg: <FiMinimize2 size={24} /> },
  { name: "i2", svg: <FiMinus size={24} /> },
  { name: "n2", svg: <FiMinusCircle size={24} /> },
  { name: "e2", svg: <FiMinusSquare size={24} /> },
  { name: "a2", svg: <FiMonitor size={24} /> },
  { name: "l2", svg: <FiMoon size={24} /> },

  { name: "s2", svg: <FiMoreHorizontal size={24} /> },
  { name: "c2", svg: <FiMoreVertical size={24} /> },
  { name: "u2", svg: <FiMousePointer size={24} /> },
  { name: "g2", svg: <FiMove size={24} /> },
  { name: "d2", svg: <FiMusic size={24} /> },
  { name: "h2", svg: <BsCursor size={24} /> },

  { name: "k2", svg: <LuNavigation2 size={24} /> },
  { name: "x2", svg: <FiOctagon size={24} /> },
  { name: "y2", svg: <FiBox size={24} /> },
  { name: "p2", svg: <FiPaperclip size={24} /> },
  { name: "L2", svg: <FiPause size={24} /> },
  { name: "v2", svg: <MdOutlinePauseCircle size={24} /> },

  { name: "f2", svg: <FiPenTool size={24} /> },
  { name: "w2", svg: <FiPercent size={24} /> },
  { name: "A2", svg: <FiPhone size={24} /> },
  { name: "C2", svg: <FiPhoneCall size={24} /> },
  { name: "F2", svg: <FiPhoneForwarded size={24} /> },
  { name: "B2", svg: <FiPhoneIncoming size={24} /> },

  { name: "W2", svg: <FiPhoneMissed size={24} /> },
  { name: "j2", svg: <FiPhoneOff size={24} /> },
  { name: "M2", svg: <FiPhoneOutgoing size={24} /> },
  { name: "z2", svg: <FiPieChart size={24} /> },
  { name: "V2", svg: <FiPlay size={24} /> },
  { name: "H2", svg: <FiPlayCircle size={24} /> },

  { name: "P2", svg: <FiPlus size={24} /> },
  { name: "m2", svg: <FiPlusCircle size={24} /> },
  { name: "S2", svg: <FiPlusSquare size={24} /> },
  { name: "T2", svg: <FiPocket size={24} /> },
  { name: "D2", svg: <FiPower size={24} /> },
  { name: "U2", svg: <FiPrinter size={24} /> },

  { name: "R2", svg: <FaPodcast size={24} /> },
  { name: "b2", svg: <FiRefreshCcw size={24} /> },
  { name: "O2", svg: <FiRefreshCw size={24} /> },
  { name: "G2", svg: <FiRepeat size={24} /> },
  { name: "I2", svg: <FiRewind size={24} /> },
  { name: "q2", svg: <FiRotateCcw size={24} /> },

  { name: "E2", svg: <FiRotateCw size={24} /> },
  { name: "X2", svg: <FiRss size={24} /> },
  { name: "Z2", svg: <FiSave size={24} /> },
  { name: "_2", svg: <FiScissors size={24} /> },
  { name: "N2", svg: <FiSearch size={24} /> },
  { name: "J2", svg: <FiSend size={24} /> },

  { name: "K2", svg: <FiServer size={24} /> },
  { name: "Y2", svg: <FiSettings size={24} /> },
  { name: "$2", svg: <FiShare size={24} /> },
  { name: "Q2", svg: <FiShare2 size={24} /> },
  { name: "ro", svg: <FiShield size={24} /> },
  { name: "to", svg: <FiShieldOff size={24} /> },

  { name: "oo", svg: <FiShoppingBag size={24} /> },
  { name: "no", svg: <FiShoppingCart size={24} /> },
  { name: "eo", svg: <FiShuffle size={24} /> },
  { name: "io", svg: <FiSidebar size={24} /> },
  { name: "ao", svg: <FiSkipBack size={24} /> },
  { name: "lo", svg: <FiSkipForward size={24} /> },

  { name: "so", svg: <FiSlack size={24} /> },
  { name: "co", svg: <FiSlash size={24} /> },
  { name: "uo", svg: <FiSliders size={24} /> },
  { name: "go", svg: <FiSmartphone size={24} /> },
  { name: "ko", svg: <FiSmile size={24} /> },
  { name: "ho", svg: <FiSpeaker size={24} /> },

  { name: "xo", svg: <FiSquare size={24} /> },
  { name: "yo", svg: <FiStar size={24} /> },
  { name: "po", svg: <FiTarget size={24} /> },
  { name: "vo", svg: <FiSun size={24} /> },
  { name: "Lo", svg: <BsSunrise size={24} /> },
  { name: "fo", svg: <BsSunset size={24} /> },

  { name: "wo", svg: <FiBox size={24} /> },
  { name: "Co", svg: <FiSmartphone size={24} /> },
  { name: "Fo", svg: <FiTag size={24} /> },
  { name: "Bo", svg: <FiDisc size={24} /> },
  { name: "Wo", svg: <FiTerminal size={24} /> },
  { name: "jo", svg: <FiThermometer size={24} /> },

  { name: "Mo", svg: <FiThumbsDown size={24} /> },
  { name: "Ao", svg: <FiThumbsUp size={24} /> },
  { name: "zo", svg: <FiToggleLeft size={24} /> },
  { name: "Ho", svg: <FiToggleRight size={24} /> },
  { name: "Vo", svg: <FiTool size={24} /> },
  { name: "So", svg: <FiTrash size={24} /> },
  
  { name: "mo", svg: <FiTrash2 size={24} /> },
  { name: "Po", svg: <FiTrello size={24} /> },
  { name: "To", svg: <FiTrendingDown size={24} /> },
  { name: "Do", svg: <FiTrendingUp size={24} /> },
  { name: "Uo", svg: <FiTriangle size={24} /> },
  { name: "Ro", svg: <FiTruck size={24} /> },

  { name: "bo", svg: <FiTv size={24} /> },
  { name: "Oo", svg: <FiTwitch size={24} /> },
  { name: "Go", svg: <FiTwitter size={24} /> },
  { name: "Io", svg: <FiType size={24} /> },
  { name: "qo", svg: <FiUmbrella size={24} /> },
  { name: "Eo", svg: <FiUnderline size={24} /> },

  { name: "Xo", svg: <FiUnlock size={24} /> },
  { name: "_o", svg: <FiUpload size={24} /> },
  { name: "Zo", svg: <FiHeadphones size={24} /> },
  { name: "Qo", svg: <FiUser size={24} /> },
  { name: "No", svg: <FiUserCheck size={24} /> },
  { name: "Jo", svg: <FiUserMinus size={24} /> },

  { name: "Ko", svg: <FiUserPlus size={24} /> },
  { name: "Yo", svg: <FiUsers size={24} /> },
  { name: "$o", svg: <FiUserX size={24} /> },
  { name: "rn", svg: <FiVideo size={24} /> },
  { name: "tn", svg: <FiVideoOff size={24} /> },
  { name: "on", svg: <FiVoicemail size={24} /> },

  { name: "ln", svg: <FiVolume size={24} /> },
  { name: "nn", svg: <FiVolume1 size={24} /> },
  { name: "en", svg: <FiVolume2 size={24} /> },
  { name: "an", svg: <FiVolumeX size={24} /> },
  { name: "sn", svg: <FiWatch size={24} /> },
  { name: "un", svg: <FiWifi size={24} /> },

  { name: "cn", svg: <FiWifiOff size={24} /> },
  { name: "gn", svg: <FiWind size={24} /> },
  { name: "xn", svg: <FiX size={24} /> },
  { name: "dn", svg: <GoXCircle size={24} /> },
  { name: "kn", svg: <FiXOctagon size={24} /> },
  { name: "hn", svg: <FiXSquare size={24} /> },

  { name: "yn", svg: <FiYoutube size={24} /> },
  { name: "vn", svg: <FiZap size={24} /> },
  { name: "pn", svg: <LuZapOff size={24} /> },
  { name: "Ln", svg: <FiZoomIn size={24} /> },
  { name: "fn", svg: <FiZoomOut size={24} /> },
];
