interface IconItem {
  name: string;
}

export const regularIcon: IconItem[] = [
  { name: "fi-rr-0" },
  { name: "fi-rr-acorn" },
  { name: "fi-rr-ad" },
  { name: "fi-rr-add-document" },
  { name: "fi-rr-add-folder" },
  { name: "fi-rr-add" },
  { name: "fi-rr-address-book" },
  { name: "fi-rr-address-card" },
  { name: "fi-rr-air-conditioner" },
  { name: "fi-rr-air-freshener" },
  { name: "fi-rr-airplay" },
  { name: "fi-rr-alarm-clock" },
  { name: "fi-rr-alarm-exclamation" },
  { name: "fi-rr-alarm-plus" },
  { name: "fi-rr-alarm-snooze" },
  { name: "fi-rr-album-circle-plus" },
  { name: "fi-rr-album-circle-user" },
  { name: "fi-rr-album-collection" },
  { name: "fi-rr-album" },
  { name: "fi-rr-alien" },
  { name: "fi-rr-align-center" },
  { name: "fi-rr-align-justify" },
  { name: "fi-rr-align-left" },
  { name: "fi-rr-align-slash" },
  { name: "fi-rr-ambulance" },
  { name: "fi-rr-anchor" },
  { name: "fi-rr-angel" },
  { name: "fi-rr-angle-circle-down" },
  { name: "fi-rr-angle-circle-left" },
  { name: "fi-rr-angle-circle-right" },
];

export const solidIcon: IconItem[] = [
  { name: "fi-sr-0" },
  { name: "fi-sr-acorn" },
  { name: "fi-sr-ad" },
  { name: "fi-sr-add-document" },
  { name: "fi-sr-add-folder" },
  { name: "fi-sr-add" },
  { name: "fi-sr-address-book" },
  { name: "fi-sr-address-card" },
  { name: "fi-sr-air-conditioner" },
  { name: "fi-sr-air-freshener" },
  { name: "fi-sr-airplay" },
  { name: "fi-sr-alarm-clock" },
  { name: "fi-sr-alarm-exclamation" },
  { name: "fi-sr-alarm-plus" },
  { name: "fi-sr-alarm-snooze" },
  { name: "fi-sr-album-circle-plus" },
  { name: "fi-sr-album-circle-user" },
  { name: "fi-sr-album-collection" },
  { name: "fi-sr-album" },
  { name: "fi-sr-alien" },
  { name: "fi-sr-align-center" },
  { name: "fi-sr-align-justify" },
  { name: "fi-sr-align-left" },
  { name: "fi-sr-align-slash" },
  { name: "fi-sr-ambulance" },
  { name: "fi-sr-anchor" },
  { name: "fi-sr-angel" },
  { name: "fi-sr-angle-circle-down" },
  { name: "fi-sr-angle-circle-left" },
  { name: "fi-sr-angle-circle-right" },
];

export const straightIcon: IconItem[] = [
  { name: "fi-rs-0" },
  { name: "fi-rs-acorn" },
  { name: "fi-rs-ad" },
  { name: "fi-rs-add-document" },
  { name: "fi-rs-add-folder" },
  { name: "fi-rs-add" },
  { name: "fi-rs-address-book" },
  { name: "fi-rs-address-card" },
  { name: "fi-rs-air-conditioner" },
  { name: "fi-rs-air-freshener" },
  { name: "fi-rs-airplay" },
  { name: "fi-rs-alarm-clock" },
  { name: "fi-rs-alarm-exclamation" },
  { name: "fi-rs-alarm-plus" },
  { name: "fi-rs-alarm-snooze" },
  { name: "fi-rs-album-circle-plus" },
  { name: "fi-rs-album-circle-user" },
  { name: "fi-rs-album-collection" },
  { name: "fi-rs-album" },
  { name: "fi-rs-alien" },
  { name: "fi-rs-align-center" },
  { name: "fi-rs-align-justify" },
  { name: "fi-rs-align-left" },
  { name: "fi-rs-align-slash" },
  { name: "fi-rs-ambulance" },
  { name: "fi-rs-anchor" },
  { name: "fi-rs-angel" },
  { name: "fi-rs-angle-circle-down" },
  { name: "fi-rs-angle-circle-left" },
  { name: "fi-rs-angle-circle-right" },
];

export const boldIcon: IconItem[] = [
  { name: "fi-br-0" },
  { name: "fi-br-acorn" },
  { name: "fi-br-ad" },
  { name: "fi-br-add-document" },
  { name: "fi-br-add-folder" },
  { name: "fi-br-add" },
  { name: "fi-br-address-book" },
  { name: "fi-br-address-card" },
  { name: "fi-br-air-conditioner" },
  { name: "fi-br-air-freshener" },
  { name: "fi-br-airplay" },
  { name: "fi-br-alarm-clock" },
  { name: "fi-br-alarm-exclamation" },
  { name: "fi-br-alarm-plus" },
  { name: "fi-br-alarm-snooze" },
  { name: "fi-br-album-circle-plus" },
  { name: "fi-br-album-circle-user" },
  { name: "fi-br-album-collection" },
  { name: "fi-br-album" },
  { name: "fi-br-alien" },
  { name: "fi-br-align-center" },
  { name: "fi-br-align-justify" },
  { name: "fi-br-align-left" },
  { name: "fi-br-align-slash" },
  { name: "fi-br-ambulance" },
  { name: "fi-br-anchor" },
  { name: "fi-br-angel" },
  { name: "fi-br-angle-circle-down" },
  { name: "fi-br-angle-circle-left" },
  { name: "fi-br-angle-circle-right" },
]

export const brandIcon: IconItem[] = [
  { name: "fi-brands-adobe" },
  { name: "fi-brands-facebook" },
  { name: "fi-brands-reddit" },
  { name: "fi-brands-twitter" },
  { name: "fi-brands-youtube" },
  { name: "fi-brands-linkedin" },
  { name: "fi-brands-telegram" },
  { name: "fi-brands-tik-tok" },
  { name: "fi-brands-google" },
  { name: "fi-brands-apple" },
  { name: "fi-brands-github" },
  { name: "fi-brands-discord" },
  { name: "fi-brands-vk" },
  { name: "fi-brands-pinterest" },
  { name: "fi-brands-behance" },
  { name: "fi-brands-photoshop" },
  { name: "fi-brands-dropbox" },
  { name: "fi-brands-spotify" },
  { name: "fi-brands-illustrator" },
  { name: "fi-brands-app-store-ios" },
  { name: "fi-brands-bitcoin" },
  { name: "fi-brands-line" },
  { name: "fi-brands-windows" },
  { name: "fi-brands-visual-basic" },
];